name: jobsque
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# Read more about Android versioning at https://developer.android.com/studio/publish/versioning


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  #  flutter_login_facebook: ^1.8.0
  #  flutter_facebook_auth: ^3.5.0
  #  firebase_storage: ^11.2.4
  #  google_sign_in: ^6.1.4
  #  firebase_messaging: ^14.6.4
#  firebase_auth: ^4.6.3
#  cloud_firestore: ^4.8.2
#  firebase_core: ^2.14.0


  # Chat *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*
  #  jiffy: ^6.2.1
  #  stream_chat_flutter_core: ^6.3.0
  #  flutter_svg: ^0.23.0
  #  stream_chat_flutter: ^6.3.0
  #  stream_chat: ^6.3.0



  # Design *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*
  fading_edge_scrollview: ^3.0.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  hexcolor: ^3.0.1
  iconsax: ^0.0.8
  sizer: ^2.0.15
  get: ^4.6.5


  # Files  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*
  country_code_picker: ^3.0.0
  permission_handler: ^10.2.0
  dropdown_search: ^5.0.6
  url_launcher: ^6.1.11
  image_picker: ^0.8.9
  grouped_list: ^5.1.2
  file_picker: 5.2.4
  timeago: ^3.4.0
  share: ^2.0.2
  intl: ^0.18.1
#  flutter_sms: ^2.3.3
# sms: ^0.2.4



  # State Management *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*
  provider: ^6.0.5
  path_provider: ^2.0.15


  # local database *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*
  shared_preferences: ^2.1.1
#  local_auth: ^2.1.6


  # Api *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true


  assets:
    - assets/images/createAccount/
    - assets/images/app logo/
    - assets/images/facebook/
    - assets/images/appled/
    - assets/images/google/
    - assets/images/Slack/
    - assets/images/twitte/
    - assets/images/vector/
    - assets/images/onboarding/
    - assets/images/haveNotMessage/
    - assets/images/Zoom/
    - assets/images/Password Check/
    - assets/images/flags/
    - assets/images/Pdf/
    - assets/images/profile-picture/
    - assets/images/language flags/
    - assets/images/not found/
    - assets/images/dimes profile/
    - assets/images/created Successfully/
    - assets/images/Shoope Logo/

  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # see https://flutter.dev/custom-fonts/#from-packages
